"""CaptoX EGX market universe used for Yahoo coverage testing.

The list combines the September 2026 EGX30 composition with a March 2026
EGX70 constituent list updated using the September 2026 EGX semi-annual
additions/deletions. The secondary EGX70 source exposed 69 named constituents,
so this development universe intentionally contains 99 sourced names rather
than inventing a missing 100th constituent.

This file is for development/testing of Yahoo coverage. It is not a licensed
market-data source and should be replaced by an official provider universe in
production.
"""

EGX30_SECURITIES = [
    {"symbol": "COMI", "company": "Commercial International Bank", "market_index": "EGX30"},
    {"symbol": "EAST", "company": "Eastern Company", "market_index": "EGX30"},
    {"symbol": "HELI", "company": "Heliopolis Housing", "market_index": "EGX30"},
    {"symbol": "ORHD", "company": "Orascom Development Egypt", "market_index": "EGX30"},
    {"symbol": "TMGH", "company": "Talaat Moustafa Group", "market_index": "EGX30"},
    {"symbol": "EKHO", "company": "Egypt Kuwait Holding", "market_index": "EGX30"},
    {"symbol": "HRHO", "company": "EFG Holding", "market_index": "EGX30"},
    {"symbol": "FWRY", "company": "Fawry", "market_index": "EGX30"},
    {"symbol": "RAYA", "company": "Raya Holding", "market_index": "EGX30"},
    {"symbol": "ETEL", "company": "Telecom Egypt", "market_index": "EGX30"},
    {"symbol": "CCAP", "company": "Qalaa Holdings", "market_index": "EGX30"},
    {"symbol": "ISPH", "company": "Ibnsina Pharma", "market_index": "EGX30"},
    {"symbol": "PHDC", "company": "Palm Hills Developments", "market_index": "EGX30"},
    {"symbol": "EGAL", "company": "Egypt Aluminum", "market_index": "EGX30"},
    {"symbol": "GBCO", "company": "GB Corp", "market_index": "EGX30"},
    {"symbol": "RMDA", "company": "Rameda", "market_index": "EGX30"},
    {"symbol": "ABUK", "company": "Abu Qir Fertilizers", "market_index": "EGX30"},
    {"symbol": "EFIH", "company": "e-finance", "market_index": "EGX30"},
    {"symbol": "ADIB", "company": "Abu Dhabi Islamic Bank Egypt", "market_index": "EGX30"},
    {"symbol": "EFID", "company": "Edita Food Industries", "market_index": "EGX30"},
    {"symbol": "ORAS", "company": "Orascom Construction", "market_index": "EGX30"},
    {"symbol": "JUFO", "company": "Juhayna Food Industries", "market_index": "EGX30"},
    {"symbol": "EMFD", "company": "Emaar Misr", "market_index": "EGX30"},
    {"symbol": "AMOC", "company": "Alexandria Mineral Oils", "market_index": "EGX30"},
    {"symbol": "MCQE", "company": "Misr Cement Qena", "market_index": "EGX30"},
    {"symbol": "BTFH", "company": "Beltone Holding", "market_index": "EGX30"},
    {"symbol": "MFPC", "company": "Misr Fertilizers Production Company", "market_index": "EGX30"},
    {"symbol": "ALCN", "company": "Alexandria Container & Cargo Handling", "market_index": "EGX30"},
    {"symbol": "CLHO", "company": "Cleopatra Hospital Company", "market_index": "EGX30"},
    {"symbol": "SKPC", "company": "Sidi Kerir Petrochemicals", "market_index": "EGX30"},
]

EGX70_SECURITIES = [
    {"symbol": "UEGC", "company": "Upper Egypt General Contracting", "market_index": "EGX70"},
    {"symbol": "ASCM", "company": "ASEC Company for Mining", "market_index": "EGX70"},
    {"symbol": "LCSW", "company": "Lecico Egypt", "market_index": "EGX70"},
    {"symbol": "CSAG", "company": "Canal Shipping Agencies", "market_index": "EGX70"},
    {"symbol": "OFH", "company": "Orascom Financial Holding", "market_index": "EGX70"},
    {"symbol": "ARAB", "company": "Arab Developers Holding", "market_index": "EGX70"},
    {"symbol": "COSG", "company": "Cairo Oils & Soap", "market_index": "EGX70"},
    {"symbol": "POUL", "company": "Cairo Poultry", "market_index": "EGX70"},
    {"symbol": "PRCL", "company": "General Company for Ceramic and Porcelain", "market_index": "EGX70"},
    {"symbol": "DSCW", "company": "Dice Sport & Casual Wear", "market_index": "EGX70"},
    {"symbol": "MPRC", "company": "Egyptian Media Production City", "market_index": "EGX70"},
    {"symbol": "ETRS", "company": "Egyptian Transport and Commercial Services", "market_index": "EGX70"},
    {"symbol": "EHDR", "company": "Egyptians Housing Development & Reconstruction", "market_index": "EGX70"},
    {"symbol": "ELSH", "company": "El Shams Housing & Urbanization", "market_index": "EGX70"},
    {"symbol": "EXPA", "company": "Export Development Bank of Egypt", "market_index": "EGX70"},
    {"symbol": "ISMQ", "company": "Iron and Steel for Mines and Quarries", "market_index": "EGX70"},
    {"symbol": "MCRO", "company": "Macro Group Pharmaceuticals", "market_index": "EGX70"},
    {"symbol": "MEPA", "company": "Medical Packaging Company", "market_index": "EGX70"},
    {"symbol": "ATQA", "company": "Misr National Steel - Ataqa", "market_index": "EGX70"},
    {"symbol": "MTIE", "company": "MM Group for Industry and International Trade", "market_index": "EGX70"},
    {"symbol": "OCDI", "company": "Sixth of October Development and Investment", "market_index": "EGX70"},
    {"symbol": "ZMID", "company": "Zahraa Maadi Investment & Development", "market_index": "EGX70"},
    {"symbol": "EGTS", "company": "Egyptian Resorts", "market_index": "EGX70"},
    {"symbol": "ISMA", "company": "Ismailia Misr Poultry", "market_index": "EGX70"},
    {"symbol": "ENGC", "company": "Engineering Industries", "market_index": "EGX70"},
    {"symbol": "TAQA", "company": "TAQA Arabia", "market_index": "EGX70"},
    {"symbol": "AMER", "company": "Amer Group Holding", "market_index": "EGX70"},
    {"symbol": "IEEC", "company": "Industrial Engineering Company", "market_index": "EGX70"},
    {"symbol": "SVCE", "company": "South Valley Cement", "market_index": "EGX70"},
    {"symbol": "AMIA", "company": "Al Multaka Al Araby Investments", "market_index": "EGX70"},
    {"symbol": "SCEM", "company": "Sinai Cement", "market_index": "EGX70"},
    {"symbol": "ICFC", "company": "International Company for Fertilizers and Chemicals", "market_index": "EGX70"},
    {"symbol": "KABO", "company": "El Nasr Clothes & Textiles", "market_index": "EGX70"},
    {"symbol": "MPCO", "company": "Mansoura Poultry", "market_index": "EGX70"},
    {"symbol": "SWDY", "company": "Elsewedy Electric", "market_index": "EGX70"},
    {"symbol": "ACTF", "company": "ACT Financial", "market_index": "EGX70"},
    {"symbol": "AIHC", "company": "Arabia Investments Holding", "market_index": "EGX70"},
    {"symbol": "MPCI", "company": "Memphis Pharmaceuticals", "market_index": "EGX70"},
    {"symbol": "ASPI", "company": "Aspire Capital Holding", "market_index": "EGX70"},
    {"symbol": "OBRI", "company": "El Obour Real Estate Investment", "market_index": "EGX70"},
    {"symbol": "CNFN", "company": "Contact Financial Holding", "market_index": "EGX70"},
    {"symbol": "HDBK", "company": "Housing and Development Bank", "market_index": "EGX70"},
    {"symbol": "ATLC", "company": "Al Tawfeek Leasing Company", "market_index": "EGX70"},
    {"symbol": "PHAR", "company": "EIPICO", "market_index": "EGX70"},
    {"symbol": "MASR", "company": "Madinet Masr", "market_index": "EGX70"},
    {"symbol": "IDRE", "company": "Ismailia Development and Real Estate", "market_index": "EGX70"},
    {"symbol": "DAPH", "company": "Development & Engineering Consultants", "market_index": "EGX70"},
    {"symbol": "CIEB", "company": "Credit Agricole Egypt", "market_index": "EGX70"},
    {"symbol": "ZEOT", "company": "Extracted Oils & Derivatives", "market_index": "EGX70"},
    {"symbol": "SIPC", "company": "Saba International Pharmaceutical", "market_index": "EGX70"},
    {"symbol": "MOED", "company": "Modern Education Systems", "market_index": "EGX70"},
    {"symbol": "GPIM", "company": "GPI for Urban Development", "market_index": "EGX70"},
    {"symbol": "SDTI", "company": "Sharm Dreams", "market_index": "EGX70"},
    {"symbol": "VALU", "company": "U Consumer Finance", "market_index": "EGX70"},
    {"symbol": "NCCW", "company": "Nasr Company for Civil Works", "market_index": "EGX70"},
    {"symbol": "UNIP", "company": "Universal for Paper and Packaging", "market_index": "EGX70"},
    {"symbol": "NIPH", "company": "Nile Pharmaceuticals", "market_index": "EGX70"},
    {"symbol": "AIFI", "company": "Atlas for Investment and Food Industries", "market_index": "EGX70"},
    {"symbol": "ARCC", "company": "Arabian Cement", "market_index": "EGX70"},
    {"symbol": "ELEC", "company": "Electro Cable Egypt", "market_index": "EGX70"},
    {"symbol": "ORWE", "company": "Oriental Weavers", "market_index": "EGX70"},
    {"symbol": "OIH", "company": "Orascom Investment Holding", "market_index": "EGX70"},
    {"symbol": "ELKA", "company": "El Kahera Housing", "market_index": "EGX70"},
    {"symbol": "GDWA", "company": "Gadwa for Industrial Development", "market_index": "EGX70"},
    {"symbol": "BONY", "company": "Bonyan for Development and Trade", "market_index": "EGX70"},
    {"symbol": "GOUR", "company": "Gourmet Egypt.Com Foods", "market_index": "EGX70"},
    {"symbol": "MBSC", "company": "Misr Beni Suef Cement", "market_index": "EGX70"},
    {"symbol": "EGCH", "company": "Egyptian Chemical Industries - Kima", "market_index": "EGX70"},
    {"symbol": "PRDC", "company": "Pioneers Properties for Urban Development", "market_index": "EGX70"},
]

MARKET_UNIVERSE = EGX30_SECURITIES + EGX70_SECURITIES
